In [1]:
import torch
print(torch.__version__)

2.11.0+cpu


In [2]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


## Introduction to tensors

### Creating tensors



In [3]:
# scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# get tensor back as python int
scalar.item()

7

In [6]:
#Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
# MATRIX
MATRIX = torch.tensor([[7, 8],
                      [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
MATRIX.ndim

2

In [11]:
# matrix over zeroth axis or dimension
MATRIX[0]

tensor([7, 8])

In [12]:
# MATRIX over 1st axis or dimension
MATRIX[1]

tensor([ 9, 10])

In [13]:
MATRIX.shape

torch.Size([2, 2])

In [14]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR.shape

torch.Size([1, 3, 3])

In [17]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [18]:
TENSOR = torch.tensor([[[[4, 5, 6],
                         [3, 2, 1],
                         [6, 8, 9]]]])
TENSOR

tensor([[[[4, 5, 6],
          [3, 2, 1],
          [6, 8, 9]]]])

In [19]:
TENSOR.ndim

4

In [20]:
TENSOR.shape

torch.Size([1, 1, 3, 3])

In [21]:
TENSOR[0]

tensor([[[4, 5, 6],
         [3, 2, 1],
         [6, 8, 9]]])

In [22]:
TENSOR = torch.tensor([[[[4, 5, 6], [3, 2, 1], [6, 8, 9]],
                         [[1, 2, 3], [4, 5, 6], [7, 8, 9]]]])
TENSOR

tensor([[[[4, 5, 6],
          [3, 2, 1],
          [6, 8, 9]],

         [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]])

In [23]:
TENSOR.shape

torch.Size([1, 2, 3, 3])

In [24]:
TENSOR.ndim

4

In [25]:
TENSOR[0]

tensor([[[4, 5, 6],
         [3, 2, 1],
         [6, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [26]:
TENSOR = torch.tensor([[[[4, 5, 6], [3, 2, 1], [6, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                        [[3, 4, 5], [0, 1, 2], [6, 8, 9]], [[5, 6, 7], [4, 2, 5], [6, 4, 3]]]])
TENSOR

tensor([[[[4, 5, 6],
          [3, 2, 1],
          [6, 8, 9]],

         [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]],

         [[3, 4, 5],
          [0, 1, 2],
          [6, 8, 9]],

         [[5, 6, 7],
          [4, 2, 5],
          [6, 4, 3]]]])

In [27]:
TENSOR.ndim

4

In [28]:
TENSOR.shape

torch.Size([1, 4, 3, 3])

In [29]:
TENSOR[0]

tensor([[[4, 5, 6],
         [3, 2, 1],
         [6, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[3, 4, 5],
         [0, 1, 2],
         [6, 8, 9]],

        [[5, 6, 7],
         [4, 2, 5],
         [6, 4, 3]]])

In [30]:
TENSOR = torch.tensor([[[[4, 5, 6], [3, 2, 1], [6, 8, 9]], [[1, 2, 3], [4, 5, 6], [7, 8, 9]]],
                        [[[3, 4, 5], [0, 1, 2], [6, 8, 9]], [[5, 6, 7], [4, 2, 5], [6, 4, 3]]]])
TENSOR

tensor([[[[4, 5, 6],
          [3, 2, 1],
          [6, 8, 9]],

         [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]],


        [[[3, 4, 5],
          [0, 1, 2],
          [6, 8, 9]],

         [[5, 6, 7],
          [4, 2, 5],
          [6, 4, 3]]]])

In [31]:
TENSOR.shape

torch.Size([2, 2, 3, 3])

In [32]:
TENSOR.ndim

4

In [33]:
TENSOR[0]

tensor([[[4, 5, 6],
         [3, 2, 1],
         [6, 8, 9]],

        [[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [34]:
TENSOR[1]

tensor([[[3, 4, 5],
         [0, 1, 2],
         [6, 8, 9]],

        [[5, 6, 7],
         [4, 2, 5],
         [6, 4, 3]]])

### Random Tensors

they are imp because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

In [35]:
# create a random tensor of size(3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4172, 0.9649, 0.7511, 0.1907],
        [0.2697, 0.8619, 0.5225, 0.7591],
        [0.3729, 0.5684, 0.5736, 0.0381]])

In [36]:
random_tensor.ndim

2

In [37]:
# create a random tensor with similar shape to an image tensor
random_image_tensor = torch.rand(size=(224, 224, 3)) # height, width, color channels(R, G, B)
random_image_tensor

tensor([[[0.6140, 0.4379, 0.2120],
         [0.9418, 0.0244, 0.2466],
         [0.4396, 0.4228, 0.9351],
         ...,
         [0.2144, 0.4012, 0.0056],
         [0.3570, 0.5590, 0.1729],
         [0.0039, 0.2161, 0.0116]],

        [[0.5477, 0.7793, 0.5801],
         [0.5934, 0.2957, 0.5722],
         [0.2126, 0.3305, 0.6584],
         ...,
         [0.7714, 0.9435, 0.7197],
         [0.7453, 0.0238, 0.1101],
         [0.8611, 0.5946, 0.5020]],

        [[0.0320, 0.1035, 0.9123],
         [0.2464, 0.2960, 0.8354],
         [0.6406, 0.6863, 0.1928],
         ...,
         [0.8686, 0.4084, 0.6797],
         [0.4038, 0.3688, 0.7653],
         [0.5289, 0.8313, 0.5096]],

        ...,

        [[0.7416, 0.4463, 0.9597],
         [0.3980, 0.4588, 0.0196],
         [0.4479, 0.4287, 0.5071],
         ...,
         [0.1652, 0.3056, 0.2485],
         [0.4627, 0.7427, 0.1953],
         [0.6441, 0.9787, 0.0098]],

        [[0.4987, 0.1738, 0.2431],
         [0.9853, 0.0357, 0.4792],
         [0.

In [38]:
random_image_tensor.shape, random_image_tensor.ndim

(torch.Size([224, 224, 3]), 3)

### Zeros and Ones

In [39]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [40]:
zeros*random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [41]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [42]:
ones.dtype # (default)

torch.float32

### Creating a range of tensors and tensors-like

In [43]:
#torch.range
one_to_ten = torch.arange(1, 11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [44]:
torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [45]:
stepping = torch.arange(start=5, end=950, step=50)
stepping

tensor([  5,  55, 105, 155, 205, 255, 305, 355, 405, 455, 505, 555, 605, 655,
        705, 755, 805, 855, 905])

In [46]:
# Creating tensors like
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Datatypes

**Note:** Tensor datatypes is one of the three big errors you will run into with PyTorch and Deep Learning

1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

In [47]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [48]:
float_32_tensor.dtype

torch.float32

In [49]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [50]:
float_16_tensor.dtype

torch.float16

In [51]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor
                               device=None, # what device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensors operations
float_32_tensor

tensor([3., 6., 9.])

### single precesion is 32 bit floating point
### half precision is 16
### and if you want more precise result you can even go upto 64

In [52]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [53]:
prod_float = float_16_tensor * float_32_tensor
prod_float

tensor([ 9., 36., 81.])

In [54]:
prod_float.dtype

torch.float32

In [55]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [56]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting info from tensors (tensor attributes)

1. Tensors not right datatype - to get datatype from a tensor use `tensor.dtype`
2. Tensors not right shape - to get shape from a tensor use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, use `tensor.device`

In [57]:
# create a tensor
some_tensor = torch.rand([3, 4], dtype=torch.float16)
some_tensor

tensor([[0.5513, 0.1035, 0.7153, 0.7412],
        [0.9980, 0.2637, 0.6606, 0.1436],
        [0.2852, 0.1729, 0.6382, 0.7476]], dtype=torch.float16)

In [58]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device tensor is on: {some_tensor.device}")

tensor([[0.5513, 0.1035, 0.7153, 0.7412],
        [0.9980, 0.2637, 0.6606, 0.1436],
        [0.2852, 0.1729, 0.6382, 0.7476]], dtype=torch.float16)
Datatype of tensor: torch.float16
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
- Addition
- Subtraction
- Multiplication
- Division
- Matrix multiplication

In [59]:
# Create a tensor
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [60]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [61]:
tensor

tensor([1, 2, 3])

In [62]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [63]:
# Try out pytorch inbuilt functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [64]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:
1. Element wise multiplication
2. Matrix Multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (3, 2)` won't work
* `(2, 3) @ (3, 2)` will work
* `(3, 2) @ (2, 3)` will work

2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` --> `(2, 2)`
* `(3, 2) @ (2, 3)` --> `(3, 3)`

In [65]:
torch.matmul(torch.rand(3, 2), torch.rand(3, 2))

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [66]:
torch.matmul(torch.rand(2, 3), torch.rand(3, 2))

tensor([[0.6156, 0.1052],
        [1.2118, 0.1700]])

In [67]:
# Element wise Multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [68]:
# Matrix Multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [69]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3 # the second tensor gets transposed for the eligibility of dot product

14

In [70]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
print(value)

tensor(14)
CPU times: user 2.04 ms, sys: 55 µs, total: 2.1 ms
Wall time: 6.3 ms


In [71]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 90 µs, sys: 14 µs, total: 104 µs
Wall time: 109 µs


tensor(14)

### one of the most common errors in deep learning: Shape errors

In [72]:
# Shpaes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.mm(tensor_A, tensor_B) # short for matrix multiplication

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [73]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

### To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **Transpose**

A **transpose** switches the rows of the matrix with its columns

In [74]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [76]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [75]:
torch.matmul(tensor_A, tensor_B.T).shape

torch.Size([3, 3])

### the same can be done with matrix_A in this case as well

### Finding the min, max, mean, sum, etc (tensor aggregation)

In [77]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [78]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [79]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [80]:
# Find the mean
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [81]:
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

### Finding the positional min and max

In [82]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [83]:
# find the position in tensor that has the minimum values with the argmin() --> returns index position of target tensor where the min value occurs
x.argmin()

tensor(0)

In [84]:
x[0]

tensor(0)

In [85]:
# argmax --> vice versa
x.argmax()

tensor(9)

In [86]:
x[9]

tensor(90)

### Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - return a view fo an input tensor of certain shape but keep the same memory
* stacking - combine multiple tensors on to of each other (vstack) or (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - return a view of the input with dimensions permuted (swapped) in a certain way

In [87]:
# create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [88]:
# Add an extra dimension
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [89]:
x_reshaped_1 = x.reshape(9, 1)
x_reshaped_1, x_reshaped_1.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

# product of the reshape dimensions should be equal to the number of elements

In [90]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [91]:
# Changing z changes x because a view of a tensor shares the same memory as the original input
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [92]:
# stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x])
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [93]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [94]:
#torch.squeeze() - removes all single dimensions from a target tensor
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [95]:
x_reshaped.shape

torch.Size([1, 9])

In [99]:
x_squeezed = x_reshaped.squeeze()
x_squeezed

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [101]:
x_squeezed.shape

torch.Size([9])

In [102]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
x_unsqueezed


tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [109]:
# torch.permute - rearranges the dimension of a target tensor in a specific order
x = torch.randn(2, 3, 5)
x.size()
x


tensor([[[ 0.3659, -1.3915, -0.4543, -0.3638,  2.0962],
         [ 0.4564, -0.0072, -0.1425, -2.9054,  1.3831],
         [ 0.4969, -2.2590, -0.6247,  0.5588, -0.3206]],

        [[ 0.5200,  0.2531,  1.1193, -1.3069,  0.3209],
         [ 0.1698,  1.2767,  0.7527, -1.0286, -0.2209],
         [-1.2516, -0.7262,  0.3634, -0.1529, -0.1657]]])

In [110]:
torch.permute(x, (2, 0, 1)).size()

torch.Size([5, 2, 3])

In [111]:
x

tensor([[[ 0.3659, -1.3915, -0.4543, -0.3638,  2.0962],
         [ 0.4564, -0.0072, -0.1425, -2.9054,  1.3831],
         [ 0.4969, -2.2590, -0.6247,  0.5588, -0.3206]],

        [[ 0.5200,  0.2531,  1.1193, -1.3069,  0.3209],
         [ 0.1698,  1.2767,  0.7527, -1.0286, -0.2209],
         [-1.2516, -0.7262,  0.3634, -0.1529, -0.1657]]])

In [112]:
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0-->1, 1-->2, 2-->0
print(x_original.shape)
print(x_permuted.shape)

torch.Size([224, 224, 3])
torch.Size([3, 224, 224])


### X permuted shares the same view of the original but from a different perspective of dimensions

## Indexing (selecting data from tensors)

Indexing with PyToerch is similar to indexing with NumPy

In [114]:
# create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [115]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [116]:
# Let's index on the middle bracket (dim=1)
x[0][0]

tensor([1, 2, 3])

In [117]:
#Let's index on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [119]:
# You can slo use ":" to select all of a target dimnsion
x[:, 0]

tensor([[1, 2, 3]])

In [120]:
# Get all the values of 0th and 1st dimension but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [121]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [122]:
# Get index 0 and 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [123]:
# Index on x to return 9
x[0, 2, 2]

tensor(9)

In [124]:
# Index on x to return 3, 6, 9
x[:, :, 2]

tensor([[3, 6, 9]])

### PyTorch tensors & NumPy

Numpy is a popular scientific python numerical computing library.
And because of this, Pytorch has functionality to interact with it.

* Data in Numpy, want in PyTorch tensor --> `torch.from_numpy(ndarray)`
* Pytorch tensor to numpy --> `torch.Tensor.numpy`

In [125]:
# Numpy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [127]:
# the default datatype of numpy is float64 and the torch tensor reflects it
array.dtype

dtype('float64')

In [129]:
# Change the value of array, what will this do to `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [131]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [132]:
numpy_tensor.dtype

dtype('float32')

### Reproducibility (trying to take out random out of random)

In short how our neural network learns:

`start with random numbers --> tensor operations --> update random numbers to try and make them better representations of the data --> again --> again --> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [133]:
torch.rand(3, 3)

tensor([[0.8836, 0.4542, 0.2859],
        [0.7278, 0.8633, 0.4033],
        [0.0527, 0.2997, 0.2449]])

In [134]:
import torch

# create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_A)
print(random_tensor_A == random_tensor_B)

tensor([[0.5064, 0.6887, 0.5088, 0.8369],
        [0.3300, 0.6954, 0.6279, 0.5742],
        [0.3078, 0.1615, 0.4883, 0.1382]])
tensor([[0.5064, 0.6887, 0.5088, 0.8369],
        [0.3300, 0.6954, 0.6279, 0.5742],
        [0.3078, 0.1615, 0.4883, 0.1382]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [136]:
# Let's make some random but reproducible tensors
import torch

# set the random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)

random_tensor_C = torch.rand(3, 4)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8694, 0.5677, 0.7411, 0.4294],
        [0.8854, 0.5739, 0.2666, 0.6274],
        [0.2696, 0.4414, 0.2969, 0.8317]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [137]:
# Here lets set the random seed before each time we call a random function
import torch

# set the random seed
RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


### Running tensors and PyTorch objects on the GPUs (and making faster computations)

### 1. Getting a GPU

1. Easiest - Use google colab for a free GPU. (options to upgrade as well)
2. Use your own GPU - takes a lil bit of setup and requires the investment of purchasing a GPU, there's a lot of options..
3. Use cloud computing - GCP, AWS, AZURE, these services allow you to rent computers on the cloud and access them

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documents.

### 2. Check for GPU access with PyTorch


In [1]:
# check for gpu access with pytorch
import torch
torch.cuda.is_available()

True

In [2]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [3]:
# count number of devices
torch.cuda.device_count()

1

### 3. Putting tensors and models on the GPU

The reason we want out tensors/models on the GPU is because using a GPU results in faster operations.

In [4]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3], device="cpu")
# even without device parameter it is still on cpu by default

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [5]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [6]:
# If tensor is on gpu, can;t transform it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [8]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])